server:
  port: 9000

spring:
  servlet:
    multipart:
      max-file-size: 1GB
    max-request-size: 1GB
  http:
    multipart:
      enabled: false
  security:
    user:
      name: me
      password: ok
app:
  storage:
    location: uploadDir
  car:
    location: carInformation
    file: cars.csv
  datasource:
    name: carinformation
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:~/carinformation;sql.syntax_mys=true
    username: SA
  jpa:
    database: hsql
    hibernate:
      ddl-auto: update  # validate or update
      generate-ddl: yes
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        use_jdbc_metadata_defaults: false


  # H2
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG